- name: Install Jenkins
  hosts: all
  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: install java
      become: true
      apt:
        name: default-jre

    - name: include vars
      include_vars: "all.yml"

  roles:
    - role: jenkins-role
      become: true
    # - role: sql
    #   become: true
    # - role: project
    #   become: true
