CREATE DATABASE IF NOT EXISTS tasckList;
USE tasckList;

CREATE TABLE tasck (
    ID INT NOT NULL AUTO_INCREMENT,
    TASK_NAME VARCHAR(255),
    TASK_DESC VARCHAR(255),
    IS_ACTIVE BOOL NOT NULL DEFAULT '0',

    PRIMARY KEY (ID)
);